name: "Cook_Lavender_A10_Final"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dọn dẹp tối đa ổ cứng máy ảo
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h

      - name: Cài đặt công cụ và cấu hình rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip rclone
          
          mkdir -p ~/.config/rclone
          cat << EOF > ~/.config/rclone/rclone.conf
          [gdrive]
          type = drive
          token = ${{ secrets.RCLONE_CONFIG_TOKEN }}
          EOF

      - name: Repo Init & Sync + Kéo Tree Lavender
        run: |
          # Cài công cụ repo
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          
          git config --global user.name "Neonova Solara"
          git config --global user.email "vinhhpn178@gmail.com"
          git config --global core.pager cat

          # Tạo thư mục làm việc trên SSD nội bộ
          mkdir -p ~/android10
          cd ~/android10
          
          # Init Source gốc (Bỏ qua verify, giới hạn depth=1 cho nhanh)
          repo init -u https://github.com/LineageOS/android.git -b lineage-17.1 --no-repo-verify --depth=1
          
          # TỰ ĐỘNG TẠO ROOMSERVICE.XML CHO LAVENDER
          mkdir -p .repo/local_manifests
          cat << EOF > .repo/local_manifests/roomservice.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <project name="LineageOS/android_device_xiaomi_lavender" path="device/xiaomi/lavender" remote="github" revision="lineage-17.1" />
            <project name="LineageOS/android_hardware_xiaomi" path="hardware/xiaomi" remote="github" revision="lineage-17.1" />
            <project name="TheMuppets/proprietary_vendor_xiaomi" path="vendor/xiaomi" remote="github" revision="lineage-17.1" />
            <project name="LineageOS/android_kernel_xiaomi_sdm660" path="kernel/xiaomi/sdm660" remote="github" revision="lineage-17.1" />
          </manifest>
          EOF
          
          # Tiến hành sync toàn bộ code
          repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags --show-current-branch

      - name: Đóng gói thô và Đẩy lên Google Drive Pro
        if: always() # Lỗi hay không lỗi vẫn đẩy lên để giữ thành quả
        run: |
          cd ~
          echo "Gom đống source code lại thành file tar thô (Không nén để CPU nhẹ gánh)..."
          tar -cf android10_source.tar android10
          
          echo "Bắt đầu đẩy file lên Google Drive bằng Token Production..."
          rclone copy android10_source.tar gdrive:/ -P
